FROM python:3.11-slim

WORKDIR /usr/src/app

COPY dashboard/requirements.txt .
RUN pip install --no-cache-dir -r dashboard/requirements.txt

COPY dashboard/ ./dashboard/
COPY data/ ./data/

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
