FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt requests faker

COPY scripts/batch_ingestor.py ./scripts/

ENTRYPOINT ["python", "scripts/batch_ingestor.py"]
CMD ["--interval", "300"]
